import os
import litellm

# 1. Provide your LiteLLM Proxy endpoint
os.environ["LITELLM_PROXY_API_BASE"] = "http://localhost:4000"

# 2. Provide the Virtual Key or Master Key generated by your Proxy
os.environ["LITELLM_PROXY_API_KEY"] = "sk-GtGat51VS0NO2MPX0ZS3cA"

# 3. Instruct the SDK to route everything through the proxy
litellm.use_litellm_proxy = True

# This call automatically forwards to your proxy, regardless of the model string
response = litellm.completion(
    model="gpt-5.5", # The model name your proxy recognizes
    messages=[{"role": "user", "content": "Hello proxy!"}]
)

print(response)
